### ISSUE TITLE
Won't run/install after update

### ISSUE THREAD

**Issue by InfiniteP07** [z4gunn/OctoPrint-GpioRgbController#6]
After installing the latest update the Plugin vanished and can't be installed again. This is the part of the log file where I think the issue is:

2021-07-18 12:37:18,904 - octoprint.plugin.core - ERROR - Error loading plugin gpiorgbcontroller
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 1264, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 69, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_gpiorgbcontroller/__init__.py", line 4, in <module>
    from gpiozero.pins.pigpio import PiGPIOFactory
  File "/home/pi/oprint/lib/python3.7/site-packages/gpiozero/pins/pigpio.py", line 25, in <module>
    import pigpio
ModuleNotFoundError: No module named 'pigpio'
2021-07-18 12:37:18,911 - octoprint.plugins.pluginmanager - WARNING - The plugin was installed successfully, but couldn't be found afterwards to initialize properly during runtime. Please restart OctoPrint.
2021-07-18 12:37:34,655 - octoprint.server.api.system - INFO - Performing command for core:restart: sudo service octoprint restart
2021-07-18 12:37:34,768 - octoprint.server - INFO - Shutting down...
2021-07-18 12:37:34,773 - octoprint.server.api.system - WARNING - Command for core:restart failed with return code -15:
! STDOUT: 
! STDERR:

**Comment by z4gunn** [comment]
[v0.3.3](https://github.com/z4gunn/OctoPrint-GpioRgbController/releases/tag/0.3.3) should resolve this issue

**Comment by InfiniteP07** [comment]
@z4gunn Hi, just a quick question: is the following wiring correct or am I missing something? 
I have the mosfet and switch connected to the Gpio pins as specified in your wiring diagram.
![IMG_20210723_182512](https://user-images.githubusercontent.com/84244774/126812529-6719545a-d5f6-48f5-a8d7-e40783d4ce13.jpg)

**Comment by z4gunn** [comment]
@InfiniteP07 The picture is a little hard to determine where the wires are going (especially the DC power jack since the +/- wire colors are the same.  There is also no ground connection to the PI, which can be fixed with a a jumper between the MOSFET source pin and the Pi header ground pin.   You do not need a resistor for the switch.  One end of the switch should be tied to same ground as the PI and the other end directly to an available GPIO.

**Comment by InfiniteP07** [comment]
@z4gunn It would be much easier to understand if you could add the gpio labeling like in this picture:

![126039213-7609fd9d-2ba7-40c6-b6c0-f49d6864d944_neu](https://user-images.githubusercontent.com/84244774/127354460-58531006-213f-4b7a-865f-b64627ca2cba.png)
(at least for a newbie like myself). Maybe even add that all grounds are connected.

Would it be possible to implement an option to change the type of switch in the settings of the Plugin? I would like to use a push button to toggle on/off so I can independently turn the LEDs on/off via gcode.

Thanks again for the amazing work!
